spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    username: root
    password: 123456
    dbcp2:
      max-total: 20
      max-idle: 5
      max-wait-millis: 6000
      min-idle: 2
    url: jdbc:mysql://localhost:3306/web_shopping_trolley?serverTimezone=Asia/Chongqing&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  graphql:
    schema:
      locations: "**/*.graphqls"
  flyway:
    enabled: true
    encoding: utf-8
    out-of-order: false
