spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/web_shopping_trolley?serverTimezone=Asia/Chongqing&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  graphql:
    schema:
      locations: "**/*.graphqls"
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  springfox:
    documentation:
      swagger-ui:
        enabled: true
      open-api:
        enabled:
          true
  flyway:
    enabled: true
    encoding: utf-8
    validate-on-migrate: true
    baseline-on-migrate: true
    out-of-order: true
    clean-on-validation-error: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace